apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipes-app-deployment
  labels:
    app: recipes-app
    type: deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: recipes-app
      type: pod
  template:
    metadata:
      labels:
        app: recipes-app
        type: pod
    spec:
      containers:
        - name: recipes-application
          image: hitham/recipes-application:latest
          ports:
            - containerPort: 8080